# Backend Configuration
backend:
  name: backend-1
  replicaCount: 1
  image:
    repository: esteban1930/backend-1
    pullPolicy: IfNotPresent
    tag: "1.31.0"

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  service:
    type: ClusterIP
    port: 8080

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  
  config:
    port: "8080"
    db_port: "5432"

# Frontend Configuration
frontend:
  name: frontend-1
  replicaCount: 1
  image:
    repository: esteban1930/frontend-1
    pullPolicy: IfNotPresent
    tag: "1.6.0"

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

  service:
    type: ClusterIP
    port: 80
  
  config:
    vite_backend_url: "/api"

# PostgreSQL Dependency Configuration
postgresql:
  enabled: true
  auth:
    database: "mydb"
    username: "esteban"
    password: "secret"

    ## Only set this, if you already have an existing secret in your kubernetes cluster, that you want to use
    existingSecret: ""
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Ingress Global Configuration
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths:
        backend: /api
        frontend: /

ingress-nginx:
  enabled: true
  # ingress-nginx chart values can be overriden here, for example
  # controller:
  #   replicaCount: 2
