
# my-app/values.yaml

# Backend Configuration
backend:
  name: backend-1
  replicaCount: 1
  image:
    repository: esteban1930/backend-1
    pullPolicy: IfNotPresent
    tag: "" # overridden by CI/CD pipeline

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: chart-example.local
        paths:
          - path: /api
            pathType: ImplementationSpecific

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  config:
    port: "8080"
    db_host: "my-app-postgresql"
    db_port: "5432"
    db_user: "esteban"
    db_name: "mydb"

# Frontend Configuration
frontend:
  name: frontend-1
  replicaCount: 1
  image:
    repository: esteban1930/frontend-1
    pullPolicy: IfNotPresent
    tag: "" # overridden by CI/CD pipeline

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    vite_backend_url: "http://chart-example.local/api" # Ingress domain

# PostgreSQL Dependency Configuration
postgresql:
  enabled: true
  auth:
    database: "mydb"
    username: "esteban"
    password: "secret"
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Ingress Global Configuration
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: chart-example.local
      paths:
        backend: /api
        frontend: /
