backend:
  replicaCount: 3 
  image:
    tag: "7" 
  
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"

frontend:
  image:
    tag: "1"
  replicaCount: 2

postgresql:
  primary:
    persistence:
      size: "10Gi" # Más espacio para prod

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "prod.parcial-1.local"
