backend:
  replicaCount: 3 
  image:
    tag: "v1.2.0" 
  
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"

frontend:
  replicaCount: 2

postgresql:
  primary:
    persistence:
      size: "10Gi" # Más espacio para prod
