{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts.paths.backend }}/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backend.name }}-service
                port:
                  number: {{ .Values.backend.service.port }}
          - path: {{ .Values.ingress.hosts.paths.frontend }}/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.frontend.name }}-service
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
