
backend:
  replicaCount: 1
  image:
    tag: "develop-latest"
  
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  replicaCount: 1

postgresql:
  primary:
    persistence:
      size: "2Gi"
