
backend:
  replicaCount: 1
  image:
    tag: "7"
  
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  image:
    tag: "1"
  replicaCount: 1

postgresql:
  primary:
    persistence:
      size: "2Gi"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "dev.parcial-1.local"
